#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Defines environment variables.
#
# Authors:
#   Ben O'Hara <bohara@gmail.com>
#

# Dont read global configs
unsetopt GLOBAL_RCS

# Set the path to dotzsh.
export DOTZSH="$HOME/.zsh"

# Source environment settings
source "$DOTZSH/env.zsh"

# Customize to your needs...
alias weka='cd ~/Documents/EDA/webweka'
alias gitpass='git config credential.helper store'
alias agi='sudo apt-get install'
alias gpo='git push origin'
alias gpom='git push origin master'
alias conkat='cd ~/Documents/EDA/kata/conway'
alias txn='tmux new -s'
alias txa='tmux a -t'
alias txl='tmux ls'
