#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Defines environment variables.
#
# Authors:
#   Ben O'Hara <bohara@gmail.com>
#

# Dont read global configs
unsetopt GLOBAL_RCS

# use nvim not vim
export EDITOR=nvim
export VISUAL=nvim
alias vim=nvim

# Beagelebone
alias bone='ssh root@192.168.7.2'
alias pbone='ssh debian@192.168.7.2' #temppwd

# Customize to your needs...
alias bot='cd ~/Documents/projects/sbot-gatherings'
alias gather='cd ~/Documents/projects/ssb-gathering-ui'
alias dep='cd ~/Documents/projects/depject'
alias vas='cd ~/Documents/projects/vas'
alias inu='cd ~/Documents/projects/inu'
alias pro='cd ~/Documents/projects'
alias choir='cd ~/Documents/projects/choir'
alias bay='cd ~/Documents/projects/patchbay'
alias south='cd ~/Documents/RootSystems/41South'
alias jou='cd ~/Dropbox/journal/'

alias grad='cd ~/Documents/EDA/org/grad-app'
alias gitpass='git config credential.helper store'
alias agi='sudo apt-get install'
alias txn='tmux new -s'
alias txa='tmux a -t'
alias txl='tmux ls'
alias ff='find . -type f -name'
# Git
alias gpo='git push origin'
alias glo='git pull origin'
alias gpom='git push origin master'
alias glom='git pull origin master'
#NPM registry change
alias npmeda='npm config set registry http://192.168.1.100:8080'
alias npmext='npm config set registry https://registry.npmjs.org/' 
##NPM
alias ni='npm i' 
alias ns='npm i --save' 
alias nd='npm i --save-dev' 
alias nt='npm test'

alias vim='nvim'
