#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Defines environment variables.
#
# Authors:
#   Ben O'Hara <bohara@gmail.com>
#

# Dont read global configs
unsetopt GLOBAL_RCS

# Set the path to dotzsh.
export DOTZSH="$HOME/.zsh"

# Source environment settings
source "$DOTZSH/env.zsh"

# Beagelebone
alias bone='ssh root@192.168.7.2'

# Customize to your needs...
alias kak='cd ~/Documents/EDA/kakapo'
alias kar='cd ~/Documents/EDA/karearea'
alias hi='cd ~/Documents/EDA/hihi'
alias ko='cd ~/Documents/EDA/kotare'
alias ro='cd ~/Documents/EDA/roa'
alias kea='cd ~/Documents/EDA/kea'
alias ker='cd ~/Documents/EDA/kereru'
alias weka='cd ~/Documents/EDA/webweka'
alias bot='cd ~/Documents/projects/sbot-gatherings'
alias gather='cd ~/Documents/projects/ssb-gathering-ui'
alias gitpass='git config credential.helper store'
alias agi='sudo apt-get install'
alias conkat='cd ~/Documents/EDA/kata/conway'
alias koakat='cd ~/Documents/EDA/kata/koa'
alias txn='tmux new -s'
alias txa='tmux a -t'
alias txl='tmux ls'
alias ff='find . -type f -name'
# Git
alias gpo='git push origin'
alias glo='git pull origin'
alias gpom='git push origin master'
alias glom='git pull origin master'
#NPM registry change
alias npmeda='npm config set registry http://192.168.1.100:8080'
alias npmext='npm config set registry https://registry.npmjs.org/' 
##NPM
alias ni='npm i' 
alias ns='npm i --save' 
alias nd='npm i --save-dev' 
alias nt='npm test'
